### ISSUE TITLE
ERA5 input data no longer available

### ISSUE THREAD

**Issue by tllsngnzlz** [koen-vg/stressful-weather#1]
As of now the [download](https://www.doi.org/10.11582/2022.00034) of input files is no longer possible. Is there a way of uploading those files again? Thanks in advance!

**Comment by koen-vg** [comment]
Hi, thanks for the notice! I'll get in touch with the provider serving the files and hopefully resolve the issue as soon as possible. In the mean time I thought the PyPSA-Eur authors might have uploaded cutouts for different weather years to Zenodo at some too, but I don't have time to track it down right this minute.

**Comment by koen-vg** [comment]
Should be fixed now! Feel free to get in touch again if anything isn't in order but closing for now.
